server:
  port: 5002
spring:
  datasource:
    # this is an Oracle container image
    url: jdbc:oracle:thin:@//localhost:1521/FREEPDB1 #use service name here
    username: labequiped
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        formate_sql: true
eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka




